spring.application.name=festivaldb
spring.datasource.url=jdbc:postgresql://localhost:5432/festivaldb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.enabled=true
spring.docker.compose.file=C:/Work/festivalWeb/project/docker-compose.yml
spring.docker.compose.lifecycle-management=start-only